//
//  main.cpp
//  hw1pr1
//
//  Created by Noor Thabit on 1/28/13.
//  Copyright (c) 2013 Noor Thabit. All rights reserved.
//

#include <iostream>
using namespace std;

int main()
{

   
    // insert code here...
   
    cout<<"  G    D         D\n"
        <<" CUSTOMER        E\n"
        <<"  I    S         C\n"
        <<"       IDEAS     R\n"
        <<" C     G         E\n"  
        <<"CORRECTNESS      M\n"
        <<" M        T      E\n"
        <<" PROGRAM  A      N\n"
        <<"CIN    INITIALIZATOIN\n"
        <<" LINKER   M\n"
        <<" E       DECLARATION\n"
        <<" R        N        A\n"
        <<"          T        M\n"
        <<"                   E\n";
    
    cout<<"DOWN:\n\n"
        <<"1. GUI:In computing, graphical user interface (GUI) is a type of user interface that allows users to interact with electronic devices using images rather than text commands.\n"
        <<"2. DESIGN: Program Design Language (or PDL, for short) is a method for designing and documenting methods and procedures in software. It is related to pseudocode, but unlike pseudocode, it is written in plain language without any terms that could suggest the use of any programming language or library.\n"
        <<"3. DECREMENT: The -- (decrement) operator subtracts 1 from the value of a scalar operand, or if the operand is a pointer, decreases the operand by the size of the object to which it points. The operand receives the result of the decrement operation. The operand must be a modifiable lvalue.\n"
        <<"4. COMPILER: A compiler is a computer program (or set of programs) that transforms source code written in a programming language (the source language) into another computer language (the target language, often having a binary form known as object code). The most common reason for wanting to transform source code is to create an executable program.\n"
        <<"5. STATMENT: statements are the program elements that control how and in what order objects are manipulated.\n\n"
        <<" ACROSS:\n\n"
        <<"7. LINKER: a linker or link editor is a computer program that takes one or more object files generated by a compiler and combines them into a single executable program.\n"
        <<"8. PROGRAM:A computer program (also software, or just a program or application) is a sequence of instructions written to perform a specified task with a computer.[1] A computer requires programs to function, typically executing the program's instructions in a central processor.[2] The program has an executable form that the computer can use directly to execute the instructions. The same program in its human-readable source code form, from which executable programs are derived (e.g., compiled), enables a programmer to study and develop its algorithms.\n"
        <<"9. DECLARATION: A declaration introduces one or more names into a program. Declarations can occur more than once in a program. Therefore, classes, structures, enumerated types, and other user-defined types can be declared for each compilation unit.\n"
        <<"10. CIN: cin is an object of class istream that represents the standard input stream. It corresponds to the cstdio stream stdin.\n"
        <<"11. CORRECTNESS: In particular it is not expected to be a correctness assertion for a given program implementing the algorithm on a given machine."
    
        <<"Refrences: Wikipedia.com and msdn.microsoft.com\n";
    
    return 0;
    
}

